export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'

export const FETCH_HOME_PRODUCTS = 'FETCH_HOME_PRODUCTS'

export const FETCH_USER_CART = 'FETCH_USER_CART'

export const CREATE_USER_CART = 'CREATE_USER_CART'

export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'

export const ADD_POST = 'ADD_POST'

export const FETCH_POSTS = 'FETCH_POSTS'

export const FETCH_SELECTED_POST = 'FETCH_SELECTED_POST'

export const ADMIN_LOGGED_IN = 'ADMIN_LOGGED_IN'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
